version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 3030:3030
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:3030
    depends_on:
      - db 
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'codeFoodDb'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  
  