version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'codeFoodDb'
      MYSQL_PORT: 3306
      MYSQL_USER: 'root'
      MYSQL_HOST: 'localhost'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql