# Generated by Django 3.2.11 on 2022-03-11 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_super_teacher', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ingredientsPerServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('unit', models.TextField()),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepOrder', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(blank=True, default='test.jpg', null=True, upload_to='images')),
                ('nServing', models.IntegerField(default=1)),
                ('nReactionLike', models.IntegerField(default=0)),
                ('nReactionNeutral', models.IntegerField(default=0)),
                ('nReactionDislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('ingredientsPerServing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientsPerServing', to='api.ingredientsperserving')),
                ('recipeCategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipeCategoryId', to='api.recipescategory')),
                ('steps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.steps')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
