# Generated by Django 3.2.11 on 2022-03-10 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
