# Generated by Django 3.2.11 on 2022-03-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220310_0745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListFood',
            new_name='RecipeList',
        ),
        migrations.RenameModel(
            old_name='FoodCategory',
            new_name='RecipesCategory',
        ),
    ]
