# Generated by Django 3.2.11 on 2022-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_servehistory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipelist',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='recipelist',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='servehistory',
            name='id',
            field=models.CharField(default='JS47', editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
