# Generated by Django 3.2.11 on 2022-03-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipescategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.recipescategory'),
        ),
    ]
