# Generated by Django 3.2.11 on 2022-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220312_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servehistory',
            name='id',
            field=models.CharField(default='1LMQ', editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
