# Generated by Django 3.2.11 on 2022-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipelist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelist',
            old_name='category',
            new_name='recipeCategory',
        ),
        migrations.RemoveField(
            model_name='recipelist',
            name='satisfied_count',
        ),
        migrations.AddField(
            model_name='recipelist',
            name='nReactionDislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipelist',
            name='nReactionLike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipelist',
            name='nReactionNeutral',
            field=models.IntegerField(default=0),
        ),
    ]
