# Generated by Django 3.2.11 on 2022-03-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220310_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelist',
            old_name='recipeCategory',
            new_name='recipeCategoryId',
        ),
    ]
