# Generated by Django 3.2.11 on 2022-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_servehistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servehistory',
            name='id',
            field=models.CharField(default='VASA', editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
