# Generated by Django 3.2.11 on 2022-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_recipecategory_recipelist_recipecategoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='recipeCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.recipescategory'),
        ),
        migrations.AlterField(
            model_name='recipelist',
            name='recipeCategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_id', to='api.recipescategory'),
        ),
    ]
