# Generated by Django 3.2.11 on 2022-03-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220310_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipelist',
            name='recipeCategory',
        ),
    ]
