# Generated by Django 3.2.11 on 2022-03-10 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_recipelist_recipecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='recipescategory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
