# Generated by Django 3.2.11 on 2022-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220310_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipelist',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
