# Generated by Django 3.2.11 on 2022-03-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_thumbnail_recipelist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientsPerServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('unit', models.TextField()),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='recipelist',
            name='nServing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipelist',
            name='ingredientsPerServing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientsPerServing', to='api.ingredientsperserving'),
        ),
    ]
