# Generated by Django 3.2.11 on 2022-03-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.steps'),
        ),
    ]
