# Generated by Django 3.2.11 on 2022-03-11 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_recipelist_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='image',
            field=models.ImageField(blank=True, default='test.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipelist',
            name='recipeCategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipeCategoryId', to='api.recipescategory'),
        ),
    ]
