# Generated by Django 3.2.11 on 2022-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220311_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipelist',
            name='steps',
        ),
        migrations.AddField(
            model_name='recipelist',
            name='steps',
            field=models.ManyToManyField(to='api.Steps'),
        ),
    ]
